utexas_node_access_by_role.node_type.*:
  type: config_entity
  label: 'Node access by Role node type settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
utexas_node_access_by_role.settings:
  type: config_entity
  mapping:
    redirect_path:
      type: string
      label: 'Redirect path'
